coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default: false

comment:
  layout: "reach, diff, flags, files"
  require_changes: false

flags:
  html:
    paths:
      - packages/html/
  markdown:
    paths:
      - packages/markdown/
  ai:
    paths:
      - packages/ai/
