/* auto-generated by NAPI-RS */
/// <reference types="node" />
/* eslint-disable */

export declare function applyDomRemovalsToHtml(html: Buffer, removals: ExtractDomRemovalsResult): Promise<Buffer>

export interface CrawlerHtmlToMarkdownOptions {
  cssSelectorsToRemove?: Array<string>
  contentSelectors?: Array<string>
  linkTextContentToRemove?: Array<string>
  linkHrefsToRemove?: Array<string>
  linkRelTokensToRemove?: Array<string>
  useTextDensityFilter?: boolean
}

export interface CrawlerHtmlToMarkdownResult {
  title?: string
  meta: Record<string, any>
  links: Record<string, any>
  content: string
  canonicalUrl?: string
  lang?: string
}

export declare function extractDomRemovals(htmlPages: Array<Buffer>, options?: ExtractDomRemovalsOptions | undefined | null): Promise<ExtractDomRemovalsResult>

export interface ExtractDomRemovalsOptions {
  boilerplatePatterns?: Array<string>
}

export interface ExtractDomRemovalsResult {
  cssSelectorsToRemove: Array<string>
  htmlToRemove: Array<string>
}

export declare function getContentFromHtml(htmlBuffer: Buffer, options: CrawlerHtmlToMarkdownOptions): Promise<CrawlerHtmlToMarkdownResult>

export declare function htmlToEmbeddingText(html: Buffer): Promise<string>

export interface NapiSanitizeRssHtmlOptions {
  /** When `true`, rewrite external `<img src>` URLs through the configured proxy prefix. */
  proxyImages?: boolean
  /** URL path prefix prepended to proxied image URLs (default `/proxy/`). */
  imageProxyUrlPrefix?: string
  /** Hex-encoded HMAC-SHA256 signing keys (newest first). Empty = dev mode (no sig). */
  imageProxySigningKeys?: Array<string>
}

export interface NapiSanitizeRssHtmlResult {
  /** Sanitized HTML safe for rendering. */
  html: Buffer
  /** Raw `src` of the first external `<img>` found before proxying; `undefined` when none. */
  firstImageSrc?: string
}

export type SanitizeRssHtmlResult = NapiSanitizeRssHtmlResult

export declare function sanitizePromptInjection(content: Buffer, isTitle?: boolean | undefined | null): Promise<Buffer>

export declare function sanitizeRssHtml(html: Buffer, options?: NapiSanitizeRssHtmlOptions | undefined | null): Promise<SanitizeRssHtmlResult>

export declare function sanitizeRssHtmlBatch(inputs: Array<Buffer>, options?: NapiSanitizeRssHtmlOptions | undefined | null): Promise<Array<SanitizeRssHtmlResult>>
