/* auto-generated by NAPI-RS */
/* eslint-disable */
/// <reference types="node" />

export declare function chunk(text: Buffer, options?: ChunkOptions | undefined | null): Promise<Array<Chunk>>

export declare function extractMarkdownUrls(text: Buffer): Promise<MarkdownUrls>

export interface MarkdownUrls {
  linkUrls: Array<string>
  imageUrls: Array<string>
}

export interface NapiChunk {
  level: number
  header?: string
  headers: Array<string | undefined | null>
  breadcrumb: string
  text: string
  length: number
}

export interface Chunk extends NapiChunk {}

export interface NapiChunkOptions {
  minLength?: number
  maxLength?: number
  phase?: number
  title?: string
}

export interface ChunkOptions extends NapiChunkOptions {}

export interface NapiMarkdownRenderOptions {
  allowHtml?: boolean
  nofollowLinks?: boolean
  proxyImages?: boolean
  imageProxyUrlPrefix?: string
  imageProxySigningKeys?: Array<string>
}

export declare function renderMarkdownToHtml(text: Buffer, options?: NapiMarkdownRenderOptions | undefined | null): Promise<Buffer>

export declare function renderMarkdownToHtmlBatch(inputs: Array<Buffer>, options?: NapiMarkdownRenderOptions | undefined | null): Promise<Array<Buffer>>
