/* auto-generated by NAPI-RS */
/* eslint-disable */
/// <reference types="node" />
export declare function detectAiGeneratedText(text: Buffer, confidenceThreshold?: number | undefined | null): Promise<SlopDetectionResult>

export interface NapiSlopDetectionResult {
  flagged: boolean
  confidenceScore: number
  confidenceThreshold: number
  classification: string
  detector: string
  detectorModelVersion: string
}

export interface SlopDetectionResult extends NapiSlopDetectionResult {}
