/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function detectAiGeneratedText(text: Buffer, confidenceThreshold?: number | undefined | null): Promise<NapiSlopDetectionResult>

export interface NapiSlopDetectionResult {
  flagged: boolean
  confidenceScore: number
  confidenceThreshold: number
  classification: string
  detector: string
  detectorModelVersion: string
}
