/* auto-generated by @napi-rs/cli — regenerate via `npm run build` */

export interface Chunk {
  level: number
  header?: string
  headers: Array<string | undefined | null>
  breadcrumb: string
  text: string
  length: number
}

export interface ChunkOptions {
  minLength?: number
  maxLength?: number
  phase?: number
  title?: string
}

export interface NapiSanitizeRssHtmlOptions {
  proxyImages?: boolean
  imageProxyUrlPrefix?: string
  imageProxySigningKeys?: Array<string>
}

export interface SanitizeRssHtmlResult {
  html: Buffer
  firstImageSrc?: string
}

export interface NapiMarkdownRenderOptions {
  allowHtml?: boolean
  nofollowLinks?: boolean
  proxyImages?: boolean
  imageProxyUrlPrefix?: string
  imageProxySigningKeys?: Array<string>
}

export interface MarkdownUrls {
  linkUrls: Array<string>
  imageUrls: Array<string>
}

export interface SlopDetectionResult {
  flagged: boolean
  confidenceScore: number
  confidenceThreshold: number
  classification: string
  detector: string
  detectorModelVersion: string
}

export interface ExtractDomRemovalsOptions {
  boilerplatePatterns?: Array<string>
}

export interface ExtractDomRemovalsResult {
  cssSelectorsToRemove: Array<string>
  htmlToRemove: Array<string>
}

export interface CrawlerHtmlToMarkdownOptions {
  cssSelectorsToRemove?: Array<string>
  contentSelectors?: Array<string>
  linkTextContentToRemove?: Array<string>
  linkHrefsToRemove?: Array<string>
  linkRelTokensToRemove?: Array<string>
  useTextDensityFilter?: boolean
}

export interface CrawlerHtmlToMarkdownResult {
  title?: string
  meta: Record<string, unknown>
  links: Record<string, unknown>
  content: string
  canonicalUrl?: string
  lang?: string
}

export declare function chunk(text: Buffer, options?: ChunkOptions): Promise<Array<Chunk>>
export declare function sanitizeRssHtml(
  html: Buffer,
  options?: NapiSanitizeRssHtmlOptions,
): Promise<SanitizeRssHtmlResult>
export declare function sanitizeRssHtmlBatch(
  inputs: Array<Buffer>,
  options?: NapiSanitizeRssHtmlOptions,
): Promise<Array<SanitizeRssHtmlResult>>
export declare function detectAiGeneratedText(
  text: Buffer,
  confidenceThreshold?: number,
): Promise<SlopDetectionResult>
export declare function extractDomRemovals(
  htmlPages: Array<Buffer>,
  options?: ExtractDomRemovalsOptions,
): Promise<ExtractDomRemovalsResult>
export declare function applyDomRemovalsToHtml(
  html: Buffer,
  removals: ExtractDomRemovalsResult,
): Promise<Buffer>
export declare function extractMarkdownUrls(text: Buffer): Promise<MarkdownUrls>
export declare function htmlToEmbeddingText(html: Buffer): Promise<string>
export declare function renderMarkdownToHtml(
  text: Buffer,
  options?: NapiMarkdownRenderOptions,
): Promise<Buffer>
export declare function renderMarkdownToHtmlBatch(
  inputs: Array<Buffer>,
  options?: NapiMarkdownRenderOptions,
): Promise<Array<Buffer>>
export declare function sanitizePromptInjection(
  content: Buffer,
  isTitle?: boolean,
): Promise<Buffer>
export declare function getContentFromHtml(
  htmlBuffer: Buffer,
  options: CrawlerHtmlToMarkdownOptions,
): Promise<CrawlerHtmlToMarkdownResult>
